#!/bin/bash
for N in 1000 5000 10000 15000 20000 25000 30000 35000 40000 45000 50000
do
   echo "####################################################################"
   echo "### N= " $N
   echo "../bin/distanceEdition-perf   \
      /matieres/4MMAOD6/2022-10-TP-AOD-ADN-Docs-fournis/2022-10-TP-AOD-ADN-Benchmark/GCA_024498555.1_ASM2449855v1_genomic.fna 77328790 " $N \
      " /matieres/4MMAOD6/2022-10-TP-AOD-ADN-Docs-fournis/2022-10-TP-AOD-ADN-Benchmark/GCF_000001735.4_TAIR10.1_genomic.fna 30808129 " $N 
   ../bin/distanceEdition-perf   \
      /matieres/4MMAOD6/2022-10-TP-AOD-ADN-Docs-fournis/2022-10-TP-AOD-ADN-Benchmark/GCA_024498555.1_ASM2449855v1_genomic.fna 77328790 $N \
      /matieres/4MMAOD6/2022-10-TP-AOD-ADN-Docs-fournis/2022-10-TP-AOD-ADN-Benchmark/GCF_000001735.4_TAIR10.1_genomic.fna 30808129 $N 
done
